apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: tofutf

deploy:
  helm:
    releases:
      - name: tofutf
        chartPath: charts/tofutf
        valuesFiles:
          - charts/tofutf/values.yaml
          - charts/tofutf/test-values.yaml
        version: 0.3.11
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_ghcr_io_tofutf_tofutf_tofutfd }}"

build:
  platforms: ["linux/amd64"]
  artifacts:
  - image: ghcr.io/tofutf/tofutfd
    ko:
      fromImage: ghcr.io/tofutf/tofutf/tofutf-base:v1.0.0
      main: ./cmd/tofutfd
      labels:
        org.opencontainers.image.licenses: MPL-2.0
        org.opencontainers.image.revision: "{{.GITHUB_SHA}}"
        org.opencontainers.image.source: "{{.GITHUB_SERVER_URL}}/{{.GITHUB_REPOSITORY}}"

portForward:
  - resourceType: service
    resourceName: tofutf
    namespace: default
    port: 80
    localPort: 8080
    address: 0.0.0.0