apiVersion: v1
kind: Service
metadata:
  name: gitea
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
    - name: "222"
      port: 222
      targetPort: 22
  selector:
    app: gitea
