name: 'devcontainer' 
on:
  push:
    branches:
      - main


permissions:
  contents: read

jobs:
  build:
    name: Build Dev Container
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - name: Checkout (GitHub)
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pre-build dev container image
        uses: devcontainers/ci@a56d055efecd725e8cfe370543b6071b79989cc8 # v0.3.1900000349
        with:
          imageName: ghcr.io/tofutf/tofutf/devcontainer
          cacheFrom: ghcr.io/tofutf/tofutf/devcontainer
          push: always
          subFolder: .github