name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize


permissions:
  contents: read

jobs:
  main:
    name: Semantic Pull Request
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit
      - uses: step-security/action-semantic-pull-request@cc51624c7660c6b0e604869f8f7201c630fccaf0 # v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}