name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize


permissions:
  contents: read

jobs:
  main:
    name: Semantic Pull Request
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit
      - uses: step-security/action-semantic-pull-request@b7cd9b10bdd0e92fedf4fda525ff9cf433ca3c1c # v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}