name: releaser

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: write
  packages: write
  issues: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      flags: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Set up yq
        env: 
          VERSION: v4.34.2
          BINARY: yq_linux_amd64
        run: | 
          wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}.tar.gz -O - |\
            tar xz
          sudo mv ${BINARY} /usr/bin/yq
      - uses: ko-build/setup-ko@v0.6
      - name: publish-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          make publish VERSION=${{ github.ref_name }}
      - name: publish-snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: |
          make publish